package main

import (
	"student-portal/database"
	"student-portal/routes"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/logger"
	
	_ "student-portal/docs" // Swagger docs (generated by swag init)
	fiberSwagger "github.com/swaggo/fiber-swagger" // ✅ correct import
)

// @title Student Portal API
// @version 1.0
// @description This is the API documentation for the Student Portal project.
// @host localhost:3000
// @BasePath /

// @schemes http
func main() {
	// engine := html.New("./views", ".html")

	app := fiber.New()

	app.Use(logger.New())

	database.Connect()
	database.Migrate()
	routes.SetupRoutes(app)
	app.Static("/swagger", "./docs")                    // ✅ Serve static docs
	app.Get("/swagger/*", fiberSwagger.WrapHandler)
	app.Listen(":3000")
}
