basePath: /
host: localhost:3000
info:
  contact: {}
  description: This is the API documentation for the Student Portal project.
  title: Student Portal API
  version: "1.0"
paths: {}
schemes:
- http
swagger: "2.0"
